### ISSUE TITLE
[Documentation Files Archive]

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_HPA#1]
![cruise00000](https://user-images.githubusercontent.com/14296774/48161244-133dcb00-e2a8-11e8-8703-61a49e585304.jpg)
![cruise00001](https://user-images.githubusercontent.com/14296774/48161245-133dcb00-e2a8-11e8-9dae-c94e50221970.jpg)
![cruise00002](https://user-images.githubusercontent.com/14296774/48161246-133dcb00-e2a8-11e8-9cd1-eec2a9c9889d.jpg)
![cruise00003](https://user-images.githubusercontent.com/14296774/48161248-133dcb00-e2a8-11e8-8aa0-c6572a4124d3.jpg)

**Comment by RELNO** [comment]
Here an update of the general info:
-Process description
-Diagram of the intended ABM model

(see pdf for extended info)
[Process Diagram.pdf](https://github.com/CityScope/CSL_Hamburg_HPA/files/2576754/Process.Diagram.pdf)

![page_1](https://user-images.githubusercontent.com/44843769/48421825-8d18fd00-e75d-11e8-9ad6-4ecf2be38ff3.jpg)
![page_2](https://user-images.githubusercontent.com/44843769/48421826-8d18fd00-e75d-11e8-94f5-d95989454126.jpg)
![page_3](https://user-images.githubusercontent.com/44843769/48421827-8d18fd00-e75d-11e8-9c0c-dab30d0cb21c.jpg)
![page_4](https://user-images.githubusercontent.com/44843769/48421828-8d18fd00-e75d-11e8-8690-1ae509d6c3f6.jpg)

**Comment by JesusLopezBaeza** [comment]
[Gama Model_case area.zip](https://github.com/CityScope/CSL_Hamburg_HPA/files/2568262/Gama.Model_case.area.zip)

Here the shapefile layers of the [project area](https://github.com/CityScope/CSL_Hamburg_HPA/issues/2#issue-378782228).

**Comment by JesusLopezBaeza** [comment]
![stats-01](https://user-images.githubusercontent.com/44843769/48419709-efbbca00-e758-11e8-814f-9961b7cf8146.jpg)

Here the input data to work with:
-Ship Schedules: contains the arrival and departure time of every ship until the end of the season 2019. (which terminal, capacity of passengers, size, speed, amount of sprinters running and percentage of people going to the train station).
[#Ship Schedules.xlsx](https://github.com/CityScope/CSL_Hamburg_HPA/files/2576619/Ship.Schedules.xlsx)

-Terminal Timeline: contains data about inner terminal operations (amount of buses and taxis coming in and out, amount of people checkin in and out, waiting times, etc.)
[#Terminal Timeline.xlsx](https://github.com/CityScope/CSL_Hamburg_HPA/files/2576620/Terminal.Timeline.xlsx)

-Passenger Behavior: contains data about passengers while they stay in the city. (transport means used to go to the terminal, overnights in hamburg, activities, and qualitative data).
[#Passeger Behavior.xlsx](https://github.com/CityScope/CSL_Hamburg_HPA/files/2576618/Passeger.Behavior.xlsx)

**Comment by agrignard** [comment]
At some point it can be a good idea to migrate and maybe synthesise those file in the wiki (which is typically the place to put this kind of technical document) . Issues are more use to iterate and implement new feature related to code.

Keep in mind that to put image in a wiki you need to refer to the path of this image in the wiki repo so you need to clone the wiki repo and push those file in the repo i

Here is the link for the repo
https://github.com/CityScope/CSL_Hamburg_HPA.wiki.git

**Comment by RELNO** [comment]
@agrignard good point, done in wiki repo: https://github.com/CityScope/CSL_Hamburg_HPA/wiki
We of course need to organize the wiki better , but for now the wiki repo holds text/images from here.
