### ISSUE TITLE
plan.tif mising 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#13]
The file Site Plan.tif is missing in the repo

**Comment by JesusLopezBaeza** [comment]
Hi Arnaud, 
The file was too big to upload so I lowered the resolution. You can find it now in the correct path

**Comment by agrignard** [comment]
You might not have too put a .tif which indeed can be very heavy. A .tif contains a lot of meta information . Once it s well cropped to the right Area a simple jpg or png is enough and we can then have a high resolution image
