### ISSUE TITLE
info.gaml not compiling

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#17]
I see that this looks like a skelton of a model , however I prefer to keep model that compiles. 

Would it be possible to work a bit on the structure so that at least it compiles? Even if nothing is instanciated ?

**Comment by JesusLopezBaeza** [comment]
That was the first brainstorming on how many agents to have and how they should be related. At this stage I'd suggest just to delete it, since the new compiling models were developed from there.
