### ISSUE TITLE
HBF_MultiScale improvement

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#18]
Would it be possible to have a background in order to contextualize this model? right now it's a bit hard to know where it is? Maybe a simple georeferenced map?

**Comment by JesusLopezBaeza** [comment]
Same as issue #19, there is a dark background and a georreferenced image of the area as the background (Site Plan.tif). Is it maybe a rendering problem?

**Comment by agrignard** [comment]
which layer is it?

**Comment by JesusLopezBaeza** [comment]
Issue [#19](https://github.com/CityScope/CSL_Hamburg_HPA/issues/19) continues this discussion
