### ISSUE TITLE
HBF_Multiscale file missing

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#20]
2 occurrences in 2 agents at cycle 0: File denoted by /external/hbf-model/Intervention-Plaza/Intervention_modified.tif not found.
in file<point, int> intervention_plan <- file<point, int>(show_plan + 'Intervention_modified.tif') ;
/Users/Arno/Projects/GitHub/CSL_Hamburg_HPA/CSL_Hamburg_HPA_GAMA/models/external/hbf-model/Intervention-Plaza/Intervention_modified.tif
/Users/Arno/Projects/GitHub/CSL_Hamburg_HPA/CSL_Hamburg_HPA_GAMA/models/external/hbf-model/Intervention-Plaza/Intervention_modified.tif
in initializing attribute intervention_plan
in agents Simulation 0, Port City Model0

**Comment by JesusLopezBaeza** [comment]
I noticed that folders can't be renamed on Github? The /Intervention-Plaza folder in the route is named /intervention here.

**Comment by RELNO** [comment]
You need to force git to change it with `git mv hello.txt Hello.txt` https://stackoverflow.com/questions/10523849/changing-capitalization-of-filenames-in-git
