### ISSUE TITLE
User interaction on touchable

### ISSUE THREAD

**Issue by JesusLopezBaeza** [CityScope/CSL_Hamburg_HPA#21]
@agrignard we noticed issues with the user interaction when the model is running on a touch-table computer. 

On a laptop, when clicking on the 'bus shuttles' with the mouse, one can move, copy and delete them. 

However, since thouch-tables have no mouse, these interactions misbehave. Tapping the screen is equivalent to clicking with the mouse, but there's no cursor.

I'm guessing the issue is referring to these interactions through '#user_location'. Is there a way to re-model these interactions using the position of the 'clicks' unrelated to the position of a mouse?

**Comment by agrignard** [comment]
@JesusLopezBaeza this is more related to a general GAMA question so I would suggest you to create an issue on the GAMA platform Github describin gin detailled your problem (providing a minimal example so we can reproduce it and help you to solve it).

https://github.com/gama-platform/gama/issues

**Comment by JesusLopezBaeza** [comment]
https://github.com/gama-platform/gama/issues/2613

**Comment by agrignard** [comment]
Can you provide a link to a model or the part of the model copy/paste directly in the issue? Without this it's impossible for the GAMA team to replicate it

**Comment by JesusLopezBaeza** [comment]
They found it! It was one of the default models in the Gama library

**Comment by agrignard** [comment]
OK so I let you close this issue with the correspondign commit

**Comment by JesusLopezBaeza** [comment]
It works by modifying the action 'click' into 'double click', and tapping the screen of the touchable device with two fingers for 'picking' and 'dropping' the objects
