### ISSUE TITLE
Project upload 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#3]
@JesusLopezBaeza as discussed in our last meeting, it would be great if you could upload your code in this repo (and maybe the data if you can reduce the isze a bit) s we can start to haeva look at it and collaborate together on the project.

Time is flying and if we want to have some strong bases to discuss and present in January in would be great to start as soon as possible

**Comment by JesusLopezBaeza** [comment]
Hi @agrignard @RELNO,
I'm uploading the Zip file of the 3 test models I'm working with, together with the shapefile layers. 
1. Interactive move Terminals: Simple model to test how to move and copy destination points while the simulation is running.
2. Multi-Level: The entire model including the city, terminals, and people.
3. HBF Detail: A zoom in the central station area, intended to represent people coming in and out of the trains and going to the bus shuttle/taxis

[Test_3.zip](https://github.com/CityScope/CSL_Hamburg_HPA/files/2592230/Test_3.zip)

**Comment by agrignard** [comment]
@JesusLopezBaeza The usage of Github doesn't consist in adding a zip file in an issue

The idea is to put your code in the repository so people can see your code, review it, comment it, run it and eventually modify it. The idea is that the code is part of the repo so we can see what has been changed together and report what is not working.

For this time I did the commit for you here 
https://github.com/CityScope/CSL_Hamburg_HPA/commit/2764dba3ef1bdb59e3844ef1e8d75661ad713766

Here I just push the GAMA Project however as it is I can see that it will already not work as it is pointing to file that are locally in your computer (just an example but there are many of them
file shepefile_Buildings <- file("C:/Users/hij044_admin/Google Drive/09 PCM - Public/Working Materials/Gama Model_all Hamburg/buildings.shp");)

What we want is to have in this repo a model that work by itself without having to edit the path locally or point to some remote cloud files.

I would maybe suggest you to read this
https://guides.github.com/introduction/flow/

Then you can pull the last commit of the master, make the modification so it works and then do a Pull Request so we can integrate your modif in the master.

Also  don't hesitate to ask any question even if it's realted to the usage of Github and not to the project itself (ideally through the form of an issue in Github and we can see how to move forward together)
