### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#6]
@JesusLopezBaeza some suggestion/remark on the global structure of the project

Would it be possible to describe (ideally in the wiki) what are the goal of the 3 different models

- HBF_Detail.gaml 
- Interactive_Move_Terminals_Test_1.gaml => 
- Multi-Level_Ready.gaml

**Comment by JesusLopezBaeza** [comment]
@agrignard Sure, find them [here](https://github.com/CityScope/CSL_Hamburg_HPA/wiki/FILES)
