### ISSUE TITLE
HBF_Details.gaml compiling but not doing anything

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Hamburg_HPA#7]
When running this model it seems that nothing happens

**Comment by JesusLopezBaeza** [comment]
@agrignard Try [this branch](https://github.com/CityScope/CSL_Hamburg_HPA/tree/JLopez-Tourist-searching-destination-with-perception/CSL_Hamburg_HPA_GAMA). It is supposed to represent trains arriving randomly, so it may take a bit for the trains to arrive.

**Comment by agrignard** [comment]
As a rule of thumb It would be better t have waht is working in the master. I cannot explore all the branch.

The idea of branching is for development and as soon as it's ready it goes to the master

**Comment by agrignard** [comment]
@JesusLopezBaeza "this branch" is not working. Did you merge it in the master? In that case as a general github workflow it's good to mention in the issue that it has been fixed (and potentially close the issue if you think it's solved)

**Comment by agrignard** [comment]
@JesusLopezBaeza ok the model is working now but what about having a train a bit sooner? Why do we have to wait so long to have a train arriving?

**Comment by JesusLopezBaeza** [comment]
@agrignard For the moment the arrival of trains is set as random. Is it possible to schedule cyclical actions every certain amount of time? It would be great to have a train coming every hour

**Comment by agrignard** [comment]
So you could use something like this in a global reflex

`````
if (cycle mod 3600 =0){
create train;
}
`````

If you want to have a finer way of managing  time you can also  have a look at this example:
https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Features/Date%20and%20Time/Simple%20Time%20definition.gaml

You will see that you can define the variable step to explicitly saying how long is a step  (by default it's 1 second)
